# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

name: Andrew Williams
job-title: Full Stack Developer

title: Hey, I'm Andrew.
description: >-
  I'm a Full Stack Developer living in Nanaimo, BC. Sometimes I build things and they end up here.
about_me: >-
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque vestibulum rhoncus dignissim. Cras viverra ac purus ac dictum. Aliquam finibus quam quis ligula convallis, vitae iaculis nulla congue. Nam cursus ornare risus, eget aliquam tellus consectetur non.


email: andrew.th.williams@gmail.com
phone: +1 250-327-2724
github_url: https://github.com/andrew-t-williams
github_url_short: github.com/andrew-t-williams
linkedin_url: https://www.linkedin.com/in/andrew-t-williams
linkedin_url_short: linkedin.com/in/andrew-t-williams

timezone_note: Nanaimo, BC - Pacific time zone (GMT-8)

domain: andrew-t-williams.github.io     # if you want to force HTTPS, put down the domain without the http: e.g. example.com
url: https://andrew-t-williams.github.io # the base hostname & protocol for your site, e.g. http://example.com

# enables {{ site.github.<> }} liquid code
plugins:
  - "jekyll-github-metadata"



# Build settings
theme: jekyll-theme-midnight
# theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
